name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: 3.7
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install requests
      - name: download meepo package
        run: |
          chmod +x ./workspace/download_meepo.py
          ./workspace/download_meepo.py
          if [ ! -f ./package/meepo_linux_amd64.tar.gz ]; then echo "failed"; fi
