name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: 3.7
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install requests
      - name: add 
        run: |
          pwd
          ls
          uname -a 
      - name: download file
        run: |
          import requests
          url = 'https://github.com/peerXu/meepo/releases/download/0.7.1/meepo_linux_amd64.tar.gz'
          name = 'meepo_linux_amd64.tar.gz'
          r = requests.get(url)
          with open(name, 'wb') as code:
            code.write(r.content)
        shell: python
      - name: check file
        run: |
          if [ -f ./workspace/meepo_linux_amd64.tar.gz ];then echo "ok"; else echo "no ok"; fi
